openapi: 3.0.0
info:
  title: BucketBingo
  version: 0.0.1
  contact:
    name: INEG
    url: 'https://www.somewhere.com'
    email: ineg@ineg.co.kr
  license:
    name: INEG
    url: 'https://www.somewhere.com/'
  description: BucketBingo API
servers:
  - url: 'http://localhost:3000'
paths:
  /boards:
    get:
      summary: 빙고판 목록 조회
      tags:
        - bucket-bingo
      responses:
        '200':
          $ref: '#/components/responses/ListBoards'
      operationId: listBoards
      parameters:
        - $ref: '#/components/parameters/authorization'
        - $ref: '#/components/parameters/pageSize'
        - $ref: '#/components/parameters/pageOffset'
      description: 빙고판 목록을 조회합니다.
    post:
      summary: 빙고판 생성
      operationId: createBoard
      responses:
        '201':
          description: Created
          content: {}
          headers:
            Location:
              schema:
                type: string
              description: 생성된 빙고 식별자(헤더 이름은 바꿔야 함)
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        $ref: '#/components/requestBodies/CreateBoard'
        description: ''
      tags:
        - bucket-bingo
      description: 빙고판을 신규 생성합니다.
  '/boards/{boardId}':
    parameters:
      - schema:
          type: string
        name: boardId
        in: path
        required: true
        description: 빙고 식별자
    get:
      summary: 빙고판 상세 조회
      tags:
        - bucket-bingo
      responses:
        '200':
          $ref: '#/components/responses/GetBoard'
      operationId: getBoard
      parameters:
        - $ref: '#/components/parameters/authorization'
      description: 빙고판을 상세 조회합니다.
    delete:
      summary: 빙고판 삭제
      operationId: deleteBoard
      responses:
        '204':
          description: No Content
      parameters:
        - $ref: '#/components/parameters/authorization'
      description: 빙고판을 삭제합니다.
      tags:
        - bucket-bingo
    put:
      summary: 빙고판 갱신
      operationId: putBoard
      responses:
        '204':
          description: No Content
      description: 빙고판의 모든 정보를 갱신합니다.
      parameters:
        - $ref: '#/components/parameters/authorization'
      requestBody:
        $ref: '#/components/requestBodies/PutBoard'
      tags:
        - bucket-bingo
  '/boards/{boardId}/start':
    parameters:
      - schema:
          type: string
        name: boardId
        in: path
        required: true
        description: 빙고 식별자
    patch:
      summary: 빙고 시작
      operationId: startBingo
      responses:
        '204':
          description: No Content
      parameters:
        - $ref: '#/components/parameters/authorization'
      tags:
        - bucket-bingo
      description: 빙고를 시작합니다.
  '/boards/{boardId}/squares/{squareId}':
    parameters:
      - schema:
          type: string
        name: boardId
        in: path
        required: true
        description: 빙고 식별자
      - schema:
          type: integer
        name: squareId
        in: path
        required: true
        description: 빙고 칸 식별자
    patch:
      summary: 빙고칸 수정
      operationId: updateSquare
      responses:
        '204':
          description: No Content
      description: 빙고칸의 상태 또는 목표 달성율을 수정합니다. (MVP에서는 상태만 수정)
      requestBody:
        $ref: '#/components/requestBodies/UpdateSquare'
      parameters:
        - $ref: '#/components/parameters/authorization'
      tags:
        - bucket-bingo
components:
  schemas:
    BingoBoard:
      title: BingoBoard
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
          nullable: true
        size:
          type: integer
          format: int32
          minimum: 5
          maximum: 10
        squares:
          type: array
          minItems: 25
          maxItems: 100
          items:
            $ref: '#/components/schemas/BingoSquare'
        status:
          $ref: '#/components/schemas/BingoBoardStatus'
        startDate:
          type: string
          format: date-time
          nullable: true
        endDate:
          type: string
          format: date-time
          nullable: true
        created:
          $ref: '#/components/schemas/UserContext'
        updated:
          $ref: '#/components/schemas/UserContext'
      required:
        - id
        - name
        - size
        - squares
        - status
        - created
        - updated
    BingoBoardStatus:
      title: BingoBoardStatus
      enum:
        - DRAFT
        - ACTIVE
        - INACTIVE
    BingoSquare:
      title: BingoSquare
      type: object
      properties:
        order:
          type: integer
          description: 각 빙고 칸의 order는 빙고 판마다 유일하므로 사실상 식별자 역할을 대체함
          format: int32
        objective:
          $ref: '#/components/schemas/BingoObjective'
        status:
          $ref: '#/components/schemas/BingoSquareStatus'
        updatedAt:
          type: string
          format: date-time
      required:
        - order
        - status
        - updatedAt
    BingoSquareStatus:
      title: BingoSquareStatus
      enum:
        - TODO
        - IN_PROGRESS
        - DONE
    BingoObjective:
      title: BingoObjective
      type: object
      properties:
        content:
          type: string
        totalCount:
          type: integer
          format: int32
          minimum: 1
        currentCount:
          type: integer
          format: int32
          minimum: 1
      required:
        - content
        - totalCount
        - currentCount
      description: '최초에 BingoSquare가 생성된 경우, objective가 설정되지 않았을 것이므로 nullable임'
    User:
      title: User
      type: object
      properties:
        id:
          type: string
      required:
        - id
    UserContext:
      title: UserContext
      type: object
      properties:
        at:
          type: string
          format: date-time
        by:
          $ref: '#/components/schemas/User'
  parameters:
    authorization:
      name: authorization
      in: header
      required: false
      schema:
        type: string
      description: 사용자 인증 정보
    pageSize:
      name: pageSize
      in: query
      required: false
      schema:
        type: integer
        format: int32
        minimum: 1
        default: 6
      description: 이번 목록 조회시 적용할 page 크기
    pageOffset:
      name: pageOffset
      in: query
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
        format: int32
      description: 현재 조회 중인 page의 오프셋
  requestBodies:
    CreateBoard:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              size:
                type: integer
                format: int32
                example: 5
                minimum: 5
                maximum: 10
              description:
                type: string
              endDate:
                type: string
                format: date-time
                description: '(정책) 최소 7일, 최대 300년'
            required:
              - name
              - size
    PutBoard:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              name:
                type: string
              description:
                type: string
              endDate:
                type: string
                format: date-time
              squares:
                type: array
                minItems: 25
                maxItems: 100
                items:
                  type: object
                  properties:
                    content:
                      type: string
                    totalCount:
                      type: string
                  required:
                    - content
                    - totalCount
            required:
              - name
              - description
              - endDate
              - squares
    UpdateSquare:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                enum:
                  - IN_PROGRESS
                  - DONE
  responses:
    ListBoards:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              items:
                type: array
                items:
                  $ref: '#/components/schemas/BingoBoard'
              totalCount:
                type: integer
                format: int64
                minimum: 0
                description: 전체 항목 개수
              pageSize:
                type: integer
                format: int64
                minimum: 1
                default: 20
                description: 현재 페이지에서 보여주는 목록의 크기
              pageOffset:
                type: integer
                format: int64
                minimum: 0
                description: 현재 페이지의 번호
              totalPageCount:
                type: integer
                format: int64
                minimum: 0
                description: 전체 페이지의 개수
            required:
              - items
              - totalCount
              - pageSize
              - pageOffset
              - totalPageCount
    GetBoard:
      description: Example response
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/BingoBoard'
tags:
  - name: bucket-bingo
    description: bucket-bingo
